### PR TITLE
Fix PteroApp

### PR DESCRIPTION
**Pull request by InvalidJoker**
I fixxed PteroApp

### CODE REVIEW

**Comment by devnote-dev** [comment]
After further debugging I've found the root cause, it was this section here:

https://github.com/PteroPackages/Pytero/blob/4fd49672e843875c880ba802378fd79cc7d03544/pytero/http.py#L80-L81

It was adding an extra `/` which affects both the application and client API... if you could change your PR to fix this, that would be great.

**Comment by InvalidJoker** [comment]
Yes

**Comment by InvalidJokerDE** [comment]
client api is working for me

**Comment by InvalidJoker** [comment]
should be fixxed

**Review by devnote-dev — APPROVED** [review]

**Pull request merged**
